quiz_system/config/routes.rb
QuizSystem::Application.routes.draw do
  devise_for :users
  
  devise_for :admin_users
  
  resources :users
  
  resources :admin_users

  resources :results, only: [:edit, :update, :index, :show, :destroy]

  resources :answers, only: []

  resources :questions, only: []

  resources :quizzes

  resources :categories
  
  resources :mains
  
  resources :mains do
    member do
      get 'quizaction'
    end
  end
  
  get "ajax/getanswer"
  
  get "ajax/getselectedanswer"
  
  get "mains/index"
  
  get "mains/quiz"
  
  post "mains/quiz"
  
  post "mains/result"
  
  post "mains/pause"
  
  root              to: 'static_pages#home'
  match '/about',   to: 'static_pages#about'
  match '/quiz',    to: 'mains#index'
  match '/quiz/category/:id', :controller => :mains, :action => :category
  match '/mains/quiz/:id', :controller => :mains, :action => :quiz

end

quiz_system/app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :correct_flag, :deleted_flag, :name, :explanation, :question_id, :score
  
  belongs_to :question
  
  validates :name, presence: true, length: { maximum: 255 }
  validates :explanation, length: { maximum: 255 }
  validates :score, presence: true
  validates_numericality_of :score, :only_integer => true
  
  def destroy
    run_callbacks :destroy do
      self.deleted_flag = true
      save
    end
  end
end

quiz_system/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @answers }
    end
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
    @answer = Answer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/new
  # GET /answers/new.json
  def new
    @answer = Answer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/1/edit
  def edit
    @answer = Answer.find(params[:id])
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(params[:answer])

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render json: @answer, status: :created, location: @answer }
      else
        format.html { render action: "new" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /answers/1
  # PUT /answers/1.json
  def update
    @answer = Answer.find(params[:id])

    respond_to do |format|
      if @answer.update_attributes(params[:answer])
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to answers_url }
      format.json { head :no_content }
    end
  end
end

quiz_system/app/helpers/answers_helper.rb
module AnswersHelper
end

quiz_system/app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :question_id %><br />
    <%= f.number_field :question_id %>
  </div>
  <div class="field">
    <%= f.label :correct_flag %><br />
    <%= f.check_box :correct_flag %>
  </div>
  <div class="field">
    <%= f.label :score %><br />
    <%= f.number_field :score %>
  </div>
  <div class="field">
    <%= f.label :explanation %><br />
    <%= f.text_area :explanation %>
  </div>
  <div class="field">
    <%= f.label :deleted_flag %><br />
    <%= f.check_box :deleted_flag %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

quiz_system/app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

quiz_system/app/views/answers/index.html.erb
<h1>Listing answers</h1>

<table>
  <tr>
    <th>Detail</th>
    <th>Question</th>
    <th>Correct flag</th>
    <th>Score</th>
    <th>Explanation</th>
    <th>Deleted flag</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @answers.each do |answer| %>
  <tr>
    <td><%= answer.detail %></td>
    <td><%= answer.question_id %></td>
    <td><%= answer.correct_flag %></td>
    <td><%= answer.score %></td>
    <td><%= answer.explanation %></td>
    <td><%= answer.deleted_flag %></td>
    <td><%= link_to 'Show', answer %></td>
    <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
    <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Answer', new_answer_path %>

quiz_system/app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

quiz_system/app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Detail:</b>
  <%= @answer.detail %>
</p>

<p>
  <b>Question:</b>
  <%= @answer.question_id %>
</p>

<p>
  <b>Correct flag:</b>
  <%= @answer.correct_flag %>
</p>

<p>
  <b>Score:</b>
  <%= @answer.score %>
</p>

<p>
  <b>Explanation:</b>
  <%= @answer.explanation %>
</p>

<p>
  <b>Deleted flag:</b>
  <%= @answer.deleted_flag %>
</p>


<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>