quiz_system/config/routes.rb
QuizSystem::Application.routes.draw do
  devise_for :users
  
  devise_for :admin_users
  
  resources :users
  
  resources :admin_users

  resources :results, only: [:edit, :update, :index, :show, :destroy]

  resources :answers, only: []

  resources :questions, only: []

  resources :quizzes

  resources :categories
  
  resources :mains
  
  resources :mains do
    member do
      get 'quizaction'
    end
  end
  
  get "ajax/getanswer"
  
  get "ajax/getselectedanswer"
  
  get "mains/index"
  
  get "mains/quiz"
  
  post "mains/quiz"
  
  post "mains/result"
  
  post "mains/pause"
  
  root              to: 'static_pages#home'
  match '/about',   to: 'static_pages#about'
  match '/quiz',    to: 'mains#index'
  match '/quiz/category/:id', :controller => :mains, :action => :category
  match '/mains/quiz/:id', :controller => :mains, :action => :quiz

end

quiz_system/app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_filter :authenticate_admin_user!, :except => [:show]
  
  # GET /quizzes
  def index
    # @quizzes = Quiz.where(:deleted_flag => false)
    @quizzes = Quiz.joins(:category).search(params[:search]).order(sort_column(Quiz, "name") + " " + sort_direction).paginate(page: params[:page])
  end

  # GET /quizzes/1
  def show
    @quiz = Quiz.find(params[:id]) 
  end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new
    @method = 'new'
     # 2.times do
       # question = @quiz.questions.build
       # 4.times { question.answers.build }
     # end
  end

  # GET /quizzes/1/edit
  def edit
    @quiz = Quiz.find(params[:id])
    @method = 'update'
  end

  # POST /quizzes
  def create
    @quiz = Quiz.new(params[:quiz])
    @quiz.update_time_allowed(params[:hours_allowed].to_i, params[:minutes_allowed].to_i)

    if @quiz.save
      @quiz.update_answer_score
      @quiz.update_completeness
      redirect_to @quiz, notice: 'Quiz was successfully created.'
    else
      render action: "new"
    end
  end

  # PUT /quizzes/1
  def update
    @quiz = Quiz.find(params[:id])
    @quiz.update_time_allowed(params[:hours_allowed].to_i, params[:minutes_allowed].to_i)

    if @quiz.update_attributes(params[:quiz])
      @quiz.update_answer_score
      @quiz.update_completeness
      redirect_to @quiz, notice: 'Quiz was successfully updated.'
    else
      render action: "edit"
    end
  end

  # DELETE /quizzes/1
  def destroy
    @quiz = Quiz.find(params[:id])
    @quiz.destroy

    redirect_to quizzes_url
  end
end

quiz_system/app/helpers/quizzes_helper.rb
module QuizzesHelper
end

quiz_system/app/views/quizzes/_answer_fields.html.erb
<div class="row">
	<div class="span8 offset1">

<div class="field">
  <div class="row">
    <div class="span2">
      <%= f.label :name, "Answer" %>
    </div>
    <div class="span6">
      <%= f.text_field :name%>
    </div>
  </div>
  <div class="row">
    <div class="span2 correct_answer">
      <%= f.label :correct_flag, "Is Correct Answer" %>
    </div>
    <div class="span3">
      <%= f.hidden_field :correct_flag, :class => "answer_correct_flag" %>
      <% if(param.correct_flag == true) %>
      	<%= button_to_function "Set as Correct Answer", "set_correct_answer(this)", :class => "btn btn-small active btn-success" %><br />
      <% else %>
      	<%= button_to_function "Set as Correct Answer", "set_correct_answer(this)", :class => "btn btn-small" %><br />
      <% end %>
    </div>
  </div>
  <!-- <div class="row">
    <div class="span2">
      <%= f.label :score %>
    </div>
    <div class="span3">
      <%= f.number_field :score %>
    </div>
  </div> -->
  <div class="row">
    <div class="span2">
      <%= f.label :explanation %>
    </div>
    <div class="span6">
      <%= f.text_area :explanation, :rows => 3 %>
    </div>
  </div>
  
  <%= f.hidden_field :_destroy %>
  <%= button_to_function "Remove Answer", "remove_answer(this)", :class => "btn btn-warning btn-medium" %><br />
</div>

	</div>
</div>

quiz_system/app/views/quizzes/_form.html.erb
<div class="row">
	<div class="span11 offset2">

<%= form_for(@quiz) do |f| %>
  <% if @quiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
      <% @quiz.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="span2">
      <%= f.label :name, "Quiz Name" %><br />
    </div>
    <div class="span6">
      <%= f.text_field :name %>
    </div>
  </div>
  
  <div class="row">
    <div class="span2">
      <%= f.label :description %><br />
    </div>
    <div class="span6">
      <%= f.text_area :description, :rows => 3 %>
    </div>
  </div>
  <div class="row">
    <div class="span2">
      <%= f.label :category_id %><br />
    </div>
    <div class="span6">
      <%= select(:quiz, :category_id, Category.all.collect {|c| [ c.name, c.id ] }, {:include_blank => 'None'}) %>
    </div>
  </div>
  <br/>
  <div class="row">
    <div class="span2">
      <%= f.label :time_allowed %><br />
    </div>
    <div class="span7">
      <%= number_field_tag :hours_allowed, (@quiz.time_allowed / 60), :in => 0..10, :class => "input-small" %> hours  
      <%= number_field_tag :minutes_allowed, (@quiz.time_allowed % 60), :in => 0..59, :class => "input-small" %> minutes
    </div>
  </div>
  <div class="row">
    <div class="span2">
      <%= f.label :max_question, "Maximum Number of Questions" %><br />
    </div>
    <div class="span3">
      <%= f.number_field :max_question %>
    </div>
  </div>
  <div class="row">
    <div class="span2">
      <%= f.label :random_flag, "Randomize Questions" %>
    </div>
    <div class="span3">
      <%= f.check_box :random_flag %>
    </div>
  </div>
  
  <br/>

  <% @quiz.questions.each do |question| %>
  	<% if(question.deleted_flag == false) %>
	  <%= f.fields_for :questions, question do |builder| %>
		<%= render 'question_fields', :f => builder, :param => question %>
	  <% end %>
	<% end %>
  <% end %>
  
  <%= button_to_add_fields "Add Question", f, :questions %>
  
  <div class="actions">
  	<% if(@method == 'new') %>
  	  <%= f.submit 'Create Quiz', :class => "btn btn-primary btn-large" %>
  	<% else %>
  	  <%= f.submit 'Update Quiz', :class => "btn btn-primary btn-large" %>
  	<% end %>
  </div>
<% end %>

	</div>
</div>

quiz_system/app/views/quizzes/_question_fields.html.erb
<div class="question">
	<h4>Question</h4><br/>
	<div class="row">
		<div class="span8 offset1">


<div class="field">
  <div class="row">
    <div class="span2">
      <%= f.label :name, "Question" %>
    </div>
    <div class="span6">
      <%= f.text_field :name%>
    </div>
  </div>
  <div class="row">
    <div class="span2">
      <%= f.label :score %>
    </div>
    <div class="span3">
      <%= f.number_field :score %>
    </div>
  </div>  
  
  <br/>
  
  <% param.answers.each do |answer| %>
    <% if(answer.deleted_flag == false) %>
      <%= f.fields_for :answers, answer do |builder| %>
	    <%= render 'answer_fields', :f => builder, :param => answer %>
      <% end %>
    <% end %>
  <% end %>
  
  <%= button_to_add_fields "Add Andswer", f, :answers %> 
  <%= f.hidden_field :_destroy %>
  <%= button_to_function "Remove Question", "remove_question(this)", :class => "btn btn-warning btn-danger" %><br/>
</div>

		</div>
	</div>
</div>
<br/>

quiz_system/app/views/quizzes/_quizzes.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<%= will_paginate %>
<table class="list_table" id="quizzes_list">
	<thead>
		<tr>
			<th><%= sortable Quiz, "name" %></th>
			<th><%= sortable Quiz, "description" %></th>
			<th><%= sortable Quiz, "categories.name", "Category" %></th>
			<th><%= sortable Quiz, "time_allowed" %></th>
			<th><%= sortable Quiz, "max_question" %></th>
			<th><%= sortable Quiz, "random_flag", "Random" %></th>
			<th><%= sortable Quiz, "completed", "Status" %></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% for quiz in @quizzes %>
			<tr>
				<td><%= truncate(quiz.name, :length => 30) %></td>
				<td><%= truncate(quiz.description, :length => 30) %></td>
				<td><%= truncate(quiz.category_name, :length => 30) %></td>
				<td><%= "#{quiz.time_allowed / 60}h #{quiz.time_allowed % 60}m" %></td>
				<td><%= quiz.max_question %></td>
				<td>
					<% if(quiz.random_flag) %>
						<%= raw("<i class=\"icon-ok-sign\"></i>") %>
					<% else %>
						<%= raw("<i class=\"icon-remove-sign\"></i>") %>
					<% end %>
				</td>
				<td>
				  <% if(!quiz.completed) %>
				    <span class="label label-warning">Incomplete!</span>
				  <% else %>
				  	<span class="label label-success">OK</span>
				  <% end %>
				</td>
				<td>
					<%= link_to raw("<i class=\"icon-eye-open\"></i>"), quiz %>
					<%= link_to raw("<i class=\"icon-pencil\"></i>"), edit_quiz_path(:id=>quiz.id) %> 
					<%= link_to raw("<i class=\"icon-remove\"></i>"), quiz, method: :delete, data: { confirm: "You sure?" } %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>
<%= will_paginate %>

quiz_system/app/views/quizzes/edit.html.erb
<h1>Editing quiz</h1>

<%= render 'form' %>

quiz_system/app/views/quizzes/index.html.erb
<% provide(:title, 'All quizzes') %>
<h1>All quizzes</h1>

<%= link_to new_quiz_path, class: "btn btn-large btn-primary" do %>
		<i class="icon-plus icon-white"></i><span class="button_text"> Add</span>
<% end %>

<br /><br />

<%= form_tag quizzes_path, :method => 'get', :id => "quizzes_search", :class => "search_form" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
  <div id="quizzes"><%= render 'quizzes' %></div>
<% end %>

quiz_system/app/views/quizzes/index.js.erb
$("#quizzes").html("<%= escape_javascript(render("quizzes")) %>");

quiz_system/app/views/quizzes/new.html.erb
<h1>New quiz</h1>
<%= render 'form' %>

quiz_system/app/views/quizzes/show.html.erb
<div class="row">
	<div class="span11 offset3">

<p id="notice"><%= notice %></p>

<p>
  <b>Quiz name:</b>
  <%= @quiz.name %>
  <% if(!@quiz.completed) %>
  	<span class="label label-warning">Incomplete!</span>
  <% end %>
</p>

<p>
  <b>Description:</b>
  <%= @quiz.description %>
</p>

<p>
  <b>Category:</b>
  <%= @quiz.category_name %>
</p>

<p>
  <b>Time allowed</b>
  <%= "#{@quiz.time_allowed / 60} hours  #{@quiz.time_allowed % 60} minutes"  %>
</p>

<% if admin_user_signed_in? %>
	<p>
	  <b>Questions randomized:</b>
	  <%= @quiz.random_flag %>
	</p>
	
	<p>
	  <b>Maximum number of question:</b>
	  <%= @quiz.max_question %>
	</p>
	
	<p>
	  <b>Questions:</b>
	  <ol> 
	    <% @quiz.questions.where(:deleted_flag => false).each do |question| %>
	      <li><%= question.name %></li>
	      
	      <ul> 
	        <% question.answers.where(:deleted_flag => false).each do |answer| %>
	          <li><%= answer.name %></li>  
	        <% end %>
	      </ul>
	 
	      <br/>
	    <% end %>
	  </ol>
	</p>
	
	<%= link_to 'Edit', edit_quiz_path(@quiz) %> |
	<%= link_to 'Back', quizzes_path %>
<% else %>
	<%= link_to 'Back', results_path(current_user) %>
<% end %>



	</div>
</div>