quiz_system/config/routes.rb
QuizSystem::Application.routes.draw do
  devise_for :users
  
  devise_for :admin_users
  
  resources :users
  
  resources :admin_users

  resources :results, only: [:edit, :update, :index, :show, :destroy]

  resources :answers, only: []

  resources :questions, only: []

  resources :quizzes

  resources :categories
  
  resources :mains
  
  resources :mains do
    member do
      get 'quizaction'
    end
  end
  
  get "ajax/getanswer"
  
  get "ajax/getselectedanswer"
  
  get "mains/index"
  
  get "mains/quiz"
  
  post "mains/quiz"
  
  post "mains/result"
  
  post "mains/pause"
  
  root              to: 'static_pages#home'
  match '/about',   to: 'static_pages#about'
  match '/quiz',    to: 'mains#index'
  match '/quiz/category/:id', :controller => :mains, :action => :category
  match '/mains/quiz/:id', :controller => :mains, :action => :quiz

end

quiz_system/app/models/result.rb
class Result < ActiveRecord::Base
  attr_accessible :comment, :end_time, :marks, :quiz_id, :retry_count, :start_time, :user_id, :time_taken, :status, :resume_time
  scope :by_user, lambda {|id| {:conditions => {:user_id => id}}}
  scope :by_quiz, lambda {|id| {:conditions => {:quiz_id => id}}}

  belongs_to :user
  belongs_to :quiz
  
  validates :marks, presence: true
  validates_numericality_of :marks, :only_integer => true
  validates_inclusion_of :marks, :in => 0..100
  validates :comment, length: { maximum: 255 }
  validates_numericality_of :status, :only_integer => true
  validates_inclusion_of :status, :in => 0..3
  
  #Constants
  STATUS_STARTED = 0
  STATUS_PAUSE = 1
  STATUS_RESUME = 2
  STATUS_ENDED = 3
  
  def self.sortable_columns
    columns = self.column_names.dup
    columns + %w[users.first_name quizzes.name]
  end
  
  def self.search(search)
    if search
      column = %w[users.first_name users.last_name quizzes.name comment marks retry_count]
      @search_text = "#{column.first} like :search"
      column.each_with_index do |name, index|
        @search_text = "#{@search_text} or #{name} like :search" unless index == 0 
      end
      where(@search_text, search: "%#{search}%")
    else
      scoped
    end
  end
    
  def self.filter_by_quiz(id)
    if id && id != '-1'
      by_quiz(id)
    else
      scoped
    end
  end
  
  def self.filter_by_user(id)
    if id && id != '-1'
      by_user(id)
    else
      scoped
    end
  end
  
end

quiz_system/app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_filter :authenticate_admin_user!, :except => [:show, :index]
  before_filter :correct_user, :only => [:show]
  before_filter :authenticate_any!, :only => [:index]
    
  def index
    @filter_quiz = Array.new
    @filter_quiz << ['', -1]
    Result.joins(:quiz).select("quiz_id, quizzes.name").uniq.map do |c|
      @filter_quiz << [c.quiz.name, c.quiz_id]
    end
    
    if admin_user_signed_in?
      @filter_user = Array.new
      @filter_user << ['', -1]
      Result.joins(:user).select("user_id, users.first_name, users.last_name").uniq.map do |c|
        @filter_user << ["#{c.user.first_name} #{c.user.last_name}", c.user_id]
      end

      @results = Result.joins(:user).joins(:quiz)
                     .filter_by_quiz(params[:filter_quiz])
                     .filter_by_user(params[:filter_user])
                     .search(params[:search])
                     .order(sort_column(Result, "id") + " " + sort_direction)
                     .paginate(page: params[:page])
    else
      @results = current_user.results.joins(:user).joins(:quiz)
                     .filter_by_quiz(params[:filter_quiz])
                     .search(params[:search])
                     .order(sort_column(Result, "id") + " " + sort_direction)
                     .paginate(page: params[:page])
    end
  end

  def show
    @result = Result.joins(:user).find(params[:id])
  end

  def edit
    @result = Result.find(params[:id])
  end
  
  # def create
    # @result = Result.new(params[:result])
# 
    # respond_to do |format|
      # if @result.save
        # format.html { redirect_to @result, notice: 'Result was successfully created.' }
        # format.json { render json: @result, status: :created, location: @result }
      # else
        # format.html { redirect_to @result }
        # format.json { render json: @result.errors, status: :unprocessable_entity }
      # end
    # end
  # end

  def update
    @result = Result.find(params[:id])

    respond_to do |format|
      if @result.update_attributes(params[:result])
        format.html { redirect_to @result, notice: 'Result was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @result = Result.find(params[:id])
    @result.destroy

    respond_to do |format|
      format.html { redirect_to results_url }
      format.json { head :no_content }
    end
  end
  
  private
    def correct_user
      if admin_user_signed_in?
        true
      else
        result = Result.find_by_id(params[:id])
        if result.nil?
          return false
        end
        
        user = User.find_by_id(result.user_id)
        redirect_to results_path unless (current_user == user)
      end
    end
end

quiz_system/app/helpers/results_helper.rb
module ResultsHelper
  def convert_status(status, marks)
    #Constants
    # STATUS_STARTED = 0
    # STATUS_PAUSE = 1
    # STATUS_ENDED = 2
    
    if((status == Result::STATUS_STARTED) || (status == Result::STATUS_RESUME))
      raw("<span class=\"label label-default\">Ongoing</span>")
    elsif(status == Result::STATUS_PAUSE)
      raw("<span class=\"label label-warning\">Paused...</span>")
    else
      if(marks >= 100)
        raw("<span class=\"label label-success\">Completed!</span>")
      else
        raw("<span class=\"label label-important\">Failed</span>")
      end
    end
  end
  
  def convert_duration(seconds)
    hours = seconds / 3600
    remaining_secs = seconds % 3600
    minutes = remaining_secs / 60
    seconds = remaining_secs % 60
    "#{hours}:#{minutes}:#{seconds}"
  end
end

quiz_system/app/views/results/_results.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<%= will_paginate %>
<table class="list_table" id="results_list">
	<thead>
		<tr>
			<th><%= sortable Result, "id", "ID" %></th>
			<th><%= sortable Result, "quizzes.name", "Quiz" %></th>
			<% if admin_user_signed_in? %>
				<th><%= sortable Result, "users.first_name", "User" %></th>
			<% end %>
			<th><%= sortable Result, "start_time" %></th>
			<th><%= sortable Result, "time_taken" %></th>
			<th><%= sortable Result, "marks" %></th>
			<th><%= sortable Result, "comment" %></th>
			<th><%= sortable Result, "retry_count", "Retry" %></th>
			<th><%= sortable Result, "status", "Status" %></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% for result in @results %>
			<tr>
				<td><%= link_to result.id, result %></td>
				<td><%= link_to truncate(result.quiz.name, :length => 20), quiz_path(result.quiz_id) %></td>
				<% if admin_user_signed_in? %>
					<td><%= link_to "#{result.user.first_name} #{result.user.last_name}", user_path(result.user_id) %></td>
				<% end %>
				<td><%= l result.start_time, :format => :long %></td>
				<td><%= result.status == Result::STATUS_ENDED ? convert_duration(result.time_taken) : "NA" %></td>
				<td><%= "#{result.marks}%" %></td>
				<td><%= truncate(result.comment, :length => 20) %></td>
				<td><%= result.retry_count %></td>
				<td><%= convert_status(result.status, result.marks) %></td>
				<td>
					<%= link_to raw("<i class=\"icon-eye-open\"></i>"), result %>
					<% if admin_user_signed_in? %>
						<%= link_to raw("<i class=\"icon-pencil\"></i>"), edit_result_path(result) %> 
						<%= link_to raw("<i class=\"icon-remove\"></i>"), result, method: :delete, data: { confirm: "You sure?" } %>
					<% else %>
						<%= link_to raw("<i class=\"icon-repeat\"></i>"), quizaction_main_path(result, :task => "restart") if result.status == Result::STATUS_ENDED %> 
						<%= link_to raw("<i class=\"icon-pencil\"></i>"), quizaction_main_path(result, :task => "continue") if result.status == Result::STATUS_PAUSE %>
					<% end %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>
<%= will_paginate %>

quiz_system/app/views/results/edit.html.erb
<% provide(:title, "Edit result") %>
<h1>Update result</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@result) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :marks %>
      <%= f.text_field :marks %>
      
      <%= f.label :comment %>
      <%= f.text_area :comment, size: "60x12" %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

quiz_system/app/views/results/index.html.erb
<% provide(:title, 'All results') %>
<h1>All results</h1>

<%= form_tag results_path, :method => 'get', :id => "results_search", :class => "search_form" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
  <% if admin_user_signed_in? %>
  <p>
    <%= select_tag :filter_user, options_for_select(@filter_user, params[:filter_user]) %>
    <%= submit_tag "Filter by user" %>
  </p>
  <% end %>
  <p>
    <%= select_tag :filter_quiz, options_for_select(@filter_quiz, params[:filter_quiz]) %>
    <%= submit_tag "Filter by quiz" %>
  </p>

  <div id="results"><%= render 'results' %></div>
<% end %>

quiz_system/app/views/results/index.js.erb
$("#results").html("<%= escape_javascript(render("results")) %>");

quiz_system/app/views/results/show.html.erb
<% provide(:title, "View Result") %>
<h1>View Result</h1>
<div class="row">
  <div class="span6 offset3">
  	<p><b>ID:</b> <%= @result.id %></p>
  	<% if admin_user_signed_in? %>
  		<p><b>User:</b> <%= link_to "#{@result.user.first_name} #{@result.user.last_name}", user_path(@result.user_id) %></p>
  		<p><b>Quiz:</b> <%= link_to @result.quiz.name, quiz_path(@result.quiz_id) %></p>
  	<% else %>
  		<p><b>User:</b> <%= "#{@result.user.first_name} #{@result.user.last_name}" %></p>
  		<p><b>Quiz:</b> <%= @result.quiz.name %></p>
  	<% end %>
  	<p><b>Start time:</b> <%= l @result.start_time, :format => :long %></p>
	<p><b>End time:</b> <%= @result.status == Result::STATUS_ENDED ? (l @result.end_time, :format => :long) : "NA" %></p>
	<p><b>Time taken:</b> <%= @result.status == Result::STATUS_ENDED ? @result.time_taken : "NA" %></p>
	<p><b>Marks:</b> <%= "#{@result.marks}%" %></p>
	<p><b>Comment:</b> <%= @result.comment %></p>
	<p><b>Retry count:</b> <%= @result.retry_count %></p>
	
	<% if admin_user_signed_in? %>
		<%= link_to edit_result_path, class: "btn btn-large btn-primary" do %>
			<i class="icon-pencil icon-white"></i><span class="button_text"> Edit</span>
		<% end %>
		<%= link_to @result, method: :delete, class: "btn btn-large btn-primary" do %>
			<i class="icon-remove icon-white"></i><span class="button_text"> Delete</span>
		<% end %>
	<% end %>
		<%= link_to results_path, class: "btn btn-large btn-primary" do %>
			<span class="button_text">Back</span>
		<% end %>
	</div>
</div>