quiz_system/config/routes.rb
QuizSystem::Application.routes.draw do
  devise_for :users
  
  devise_for :admin_users
  
  resources :users
  
  resources :admin_users

  resources :results, only: [:edit, :update, :index, :show, :destroy]

  resources :answers, only: []

  resources :questions, only: []

  resources :quizzes

  resources :categories
  
  resources :mains
  
  resources :mains do
    member do
      get 'quizaction'
    end
  end
  
  get "ajax/getanswer"
  
  get "ajax/getselectedanswer"
  
  get "mains/index"
  
  get "mains/quiz"
  
  post "mains/quiz"
  
  post "mains/result"
  
  post "mains/pause"
  
  root              to: 'static_pages#home'
  match '/about',   to: 'static_pages#about'
  match '/quiz',    to: 'mains#index'
  match '/quiz/category/:id', :controller => :mains, :action => :category
  match '/mains/quiz/:id', :controller => :mains, :action => :quiz

end

quiz_system/app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>Copyright © 2012 Snout Sdn. Bhd. All Rights Reserved.</small>
	<%= link_to image_tag("logo.png", alt: "Snout"), 'http://www.snout.com.my/' %>
	<div style="clear: both;"></div>
</footer>

quiz_system/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Quiz System", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", about_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "Quiz", mains_path %></li>
            <li><%= link_to "Result", results_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li class="divider"></li>
				<li><%= link_to "Sign out", destroy_user_session_path, method: "delete" %></li>
              </ul>
            </li>
          <% elsif admin_user_signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Settings <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Category", categories_path %></li>
                <li><%= link_to "Quiz", quizzes_path %></li>
                <li><%= link_to "Result", results_path %></li>
                <li><%= link_to "User", users_path %></li>
                <li><%= link_to "Admin", admin_users_path %></li>
              </ul>
            </li>
          	<li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_admin_user %></li>
                <li class="divider"></li>
                <li><%= link_to "Sign out", destroy_user_session_path, method: "delete" %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

quiz_system/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

quiz_system/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
      	<%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>